server.port=8081
spring.application.name=jobhunter

#config database
##
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
##
#config jwt
locpham.jwt.base64-secret=tzECSpx84vbDTl4p0/a1Xl9t+jmhXYNJIGq/sszfoz5+vvMixwHZp2/c+4/EL9bKslUbcuztgYRI0wCtQLGZHA==

#expiration : 1 day ( sc = 24 * 60 * 60)
locpham.jwt.access-token-validity-in-seconds=864000
locpham.jwt.refresh-token-validity-in-seconds=864000

#config upload file
locpham.upload-file.base-uri=file:///C:/javaRestFullApi/Upload/
###
# #default = 1MB
spring.servlet.multipart.max-file-size=50MB

# #default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB
###


###
#config
#chi so bat dau trang = 1
spring.data.web.pageable.one-indexed-parameters=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamloc2362005@gmail.com
spring.mail.password=mjiravydkzxflzpx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#config đăng nhập bằng google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

